Add shellcheck tests
Remove errors and warnings from the mache script.

diff --git a/mache b/mache
--- a/mache
+++ b/mache
@@ -13,7 +13,7 @@ mkdir -p "$HOME/.mache" &> /dev/null
 
 # Change string into a file like thing and rerun.
 test -e "$1" || {
-  eval "$0" <(printf "$@")
+  eval "$0" <(echo "$@")
   exit
 }
 
@@ -44,17 +44,17 @@ checksum() {
     echo "$@"
   })))
 
-  echo ${string_array[0]}
+  echo "${string_array[0]}"
 }
 
 # The location of the cache file.
 file="$HOME/.mache/$(checksum "$@")"
 
 # Show which file is the cache file when in debug.
-[ ! -z ${DEBUG:-} ] && >&2 printf "mache: %s\n" "$file"
+[ ! -z "${DEBUG:-}" ] && >&2 printf 'mache: %s\n' "$file"
 
 # Remove the cache when REMACHE variable is not empty.
-[ ! -z ${REMACHE:-} ] && rm -f $file 2> /dev/null
+[ ! -z "${REMACHE:-}" ] && rm -f "$file" 2> /dev/null
 
 # If the cache file exists, respond with the cache and exit
 cat "$file" 2> /dev/null && exit
@@ -67,9 +67,9 @@ tmp="$1"; shift
 
 # Run the script and cache the output while writting to stdout. (tee)
 ($tmp "$@" > "$tmp.cache" && mv -f "$tmp.cache" "$file" && chmod -w "$file") || {
-  >&2 printf "mache: failed\n"
+  >&2 printf 'mache: failed\n'
   rm -f "$file"
-  >&2 printf "mache: $tmp\n"
+  >&2 printf 'mache: %s\n' "$tmp"
   exit 1
 }
 
